FROM golang:1.24.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o auth-service ./cmd/auth

#production
FROM alpine:latest
WORKDIR /root

COPY --from=builder /app/auth-service .
EXPOSE 5000
CMD [ "./auth-service" ]